- name: mon 2eme playbook
  connection: local
  hosts: localhost
  vars:
    mot: "hello"
    personnes:
      - { nom: "xzavier" , prenom: "xzavki", ville: "paris"}
      - { nom: "sousou" , prenom: "sousou", ville: "paris"}
      - { nom: "toto" , prenom: "toto", ville: "paris"}
  tasks:
  - name: set fact
    set_fact:
      mavariable: "{{ lookup('vars', 'prj') }}"

  - name: mon premier template
    debug:
      msg: "sous_domaine:{{ variable_1 }}"
