- name: mon 2eme playbook
  hosts: soso2
  vars:
    mot: "hello"
    personnes:
      - { nom: "xzavier" , prenom: "xzavki", ville: "paris"}
      - { nom: "sousou" , prenom: "sousou", ville: "paris"}
      - { nom: "toto" , prenom: "toto", ville: "paris"}
  tasks:
  - name: mon premier template
    template:
        src: monexemple.yml.j2
        dest: /tmp/monexemple_{{ item.nom  }}.yml 
        backup: yes
    with_items:
    - "{{ personnes }}"
